version: '3.8'
services:
  backend:
    image: ghcr.io/huisu73/beatbuddy-backend:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ~/application-secret.yml:/app/application-secret.yml
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=beatbuddy
      - MYSQL_USER=beyond
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}

volumes:
  db_data: